# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 481aa8cafd2937e1273dbf3a23dfe3aab5fdd3ca9db52a761a92973debdf30d3c7a7ec168cf57b57c79bcd1c47229b32ec9e7ea165bfdc9d382ab8c60b491fc0

test:
  secret_key_base: 450717c75d7078c5a218f81f94720bfa600ac932c1b287341db9c1e51791e2a800802c33386e8b4193e3ea84e6853dacfaed8671886f0d3838590f5d4c7870f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
