version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/helloworld
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: helloworld-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: helloworld-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
